name: pdd
channels: [conda-forge, pytorch, defaults]
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  # - pytorch-cuda=12.1  # Uncomment on Linux with NVIDIA
  - pip
  - pip:
      - timm
      - medmnist
      - pyyaml
      - tqdm
      - scikit-learn
      - pytest
      - ruff
      - black
      - pre-commit