name: pdd
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - expat=2.7.1
  - libcxx=20.1.8
  - libffi=3.4.4
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.1
  - python=3.10.18
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.19.1
      - fire==0.7.1
      - fonttools==4.59.1
      - fsspec==2025.7.0
      - hf-xet==1.1.8
      - huggingface-hub==0.34.4
      - idna==3.10
      - imageio==2.37.0
      - jinja2==3.1.6
      - joblib==1.5.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - medmnist==3.0.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - packaging==25.0
      - pandas==2.3.2
      - pillow==11.3.0
      - psutil==7.0.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.7.34
      - requests==2.32.5
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - six==1.17.0
      - sympy==1.14.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.19
      - tokenizers==0.21.4
      - torch==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformers==4.55.4
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
